### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by mjt320** [OSIPI/DCE-DSC-MRI_CodeCollection#51] opened 2021-10-15 16:31 UTC
Our codecov reports look a little strange to me: only 94 source code lines tracked.
Ideally, I think we would like to measure % of contributed code tested, specifically *.py files within /src folder(?)
Grateful if anyone can help with this... Thanks.

**Comment by michaelberks** [comment] 2021-10-15 17:58
Happy to look. Might not be before ISMRM deadline though. The code cov report I just saw when I merged my code said ~250 / 450 of lines tested over the whole repo? Though this will only be for modules imported into the test suite. I was able to get code cov on QbiPy above 90% but that meant writing a lot of unit tests to cover all the margin cases and various options. The problem is, the more complete contributed code is (in terms of offering a rich set of options), the more potential execution paths there are to cover!

**Comment by notZaki** [comment] 2021-10-15 19:04
Codecov was using the wrong branch as the default. I updated it to `develop`---does it look better now?

**Comment by mjt320** [comment] 2021-10-16 09:43
Thanks both. @notZaki that looks a lot better!
We should be merging in more tests soon.

**Closed as completed** 2021-10-19 16:58 UTC
